{% set name = "nceplibs-ip" %}
{% set version = "4.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NOAA-EMC/NCEPLIBS-ip/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 799308a868dea889d2527d96a0405af7b376869581410fe4cff681205e9212b4

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - cmake
    - pkg-config >=0.21
    - make                  # [not win]
    - ninja                 # [win]
  host:
    - llvm-openmp           # [osx]
    - libgomp               # [linux]
    - nceplibs-sp
  run:
    - llvm-openmp           # [osx]
    - libgomp               # [linux]
    - nceplibs-sp

test:
  commands:
    - test -f ${PREFIX}/lib/libip_4${SHLIB_EXT} -o -f ${PREFIX}/lib/libip_d${SHLIB_EXT}  # [not win]

about:
  home: https://github.com/NOAA-EMC/NCEPLIBS-ip
  summary: The NCEP interpolation library contains Fortran 90 subprograms used for interpolating between nearly all grids used at NCEP.
  license: LGPL-3.0-only
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - EricEngle-NOAA
    - timcera
